variable "bucket_name" {}
variable "bucket_logging_be_name" {}
variable "counter_table_item" {}
variable "counter_table_name" {}
variable "github_actions_role_be_policy" {}
variable "github_actions_url" {}
variable "http_api_name" {}
variable "http_api_stage_name" {}
variable "iam_chatbot_role" {}
variable "iam_lambda_role" {}
variable "iam_role_name" {}
variable "iam_user_name" {}
variable "region" {}
variable "table_name" {}
variable "terraform_backend_policy" {}