name: Deploy Backend

on:
  push:
    branches:
      - main

permissions:
  id-token: write # this is required for requesting the JWT
  contents: read  # this is required for actions/checkout

jobs:
  terraform:
    name: Deploy Backend Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./iac

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Check Linting of Terraform files
        uses: devops-infra/action-tflint@v0.3

      - name: Run tfsec (static analysis)
        uses: aquasecurity/tfsec-action@v1.0.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::814913991817:role/GitHubActionsRole-backend
          aws-region: us-east-1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
